// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6RTjAbmoT9Nm9J3DTV8pP1FNvc9VHsI8',
    appId: '1:487544221841:web:ce6806ca0335df64fbcf30',
    messagingSenderId: '487544221841',
    projectId: 'flutter-c3a6a',
    authDomain: 'flutter-c3a6a.firebaseapp.com',
    storageBucket: 'flutter-c3a6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMf4otoOCQ04-ufa_s8RaGanhuUhjrbA',
    appId: '1:487544221841:android:85ee7475a0a13c9dfbcf30',
    messagingSenderId: '487544221841',
    projectId: 'flutter-c3a6a',
    storageBucket: 'flutter-c3a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZhmbMjAwtH8yiU6t8_UZDuuG9ZIPsYE',
    appId: '1:487544221841:ios:f11b5712b9c2dfdbfbcf30',
    messagingSenderId: '487544221841',
    projectId: 'flutter-c3a6a',
    storageBucket: 'flutter-c3a6a.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ZhmbMjAwtH8yiU6t8_UZDuuG9ZIPsYE',
    appId: '1:487544221841:ios:228fce9ca1e319befbcf30',
    messagingSenderId: '487544221841',
    projectId: 'flutter-c3a6a',
    storageBucket: 'flutter-c3a6a.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
